install numpy

In [151]:
%pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip


import numpy

In [152]:
import numpy as np

to get the version number

In [153]:
np.__version__

'2.5.1'

declare an array

In [154]:
arr=np.array(34)

demiension of array

In [155]:
arr=np.array(34)
print(arr.ndim)
arr=np.array([34,45,67,23])
print(arr.ndim)
arr=np.array([[34,45,67,23],[34,45,67,23]])
print(arr.ndim)
arr=np.array([[34,45,67,23]])
print(arr.ndim)
print(arr[0][3])
arr=np.array([[[34,45,67,23]]])
print(arr.ndim)

0
1
2
2
23
3


converting an array dimension into specified dimension

In [156]:
arr=np.array([34,45,67,23],ndmin=10)
print(arr.ndim)
arr

10


array([[[[[[[[[[34, 45, 67, 23]]]]]]]]]])

In [157]:
arr=np.array([[34,45,67,23]])
print(arr.ndim)
arr[0][3]

2


np.int64(23)

In [158]:
arr=np.array([ [34,45,67,23], [34,45,68,23]])
print(arr.ndim)
arr[1,3]

2


np.int64(23)

In [159]:
arr=np.array([ [ [34,45,67,23], [35,45,68,23] ] ])
print(arr.ndim)
arr[0,1,0]

3


np.int64(35)

In [160]:
arr=np.array([ [ [ [34,45,67,23], [35,45,68,23] ] ]])
#print(arr.ndim)
arr[0,0,0,2]

np.int64(67)

In [161]:
arr=np.array([ [[[ [[[34,45,67,23], [35,48,68,23]]]]]]])
print(arr.ndim)
#arr[0,0,0,1,0,0,2]

7


In [162]:
arr=np.array([ [ [[[34,45,67,23]]],  [[[35,48,68,23]]]] ])
print(arr.ndim)
arr[0,1,0,0,1]

5


np.int64(48)

In [163]:
arr1=np.array([ [ [[[34,45,67,23]]],  [[[35,48,68,23]]]] ])
print(arr.ndim)
arr2=np.array([[[[[34,45,67,23],[35,48,68,23]]]]])
arr2.ndim

5


5

datatype example

In [164]:
arr=np.array([1,22,3,4],dtype="S")
print(arr)
arr.dtype

[b'1' b'22' b'3' b'4']


dtype('S2')

In [165]:
arr=np.array([1,22,3,4],dtype=bool)
print(arr)
arr.dtype

[ True  True  True  True]


dtype('bool')

In [166]:
arr=np.array([1,22,-3,4],dtype="i")
print(arr)
arr.dtype

[ 1 22 -3  4]


dtype('int32')

In [167]:
arr=np.array([1,22,3,4],dtype="O")
print(arr)
arr.dtype

[1 22 3 4]


dtype('O')

In [168]:
arr=np.array([1,22,3,4],dtype="U")
print(arr)
arr.dtype

['1' '22' '3' '4']


dtype('<U2')

In [169]:
arr=np.array([1,22,3,4],dtype="V")
print(arr)
arr.dtype

TypeError: A bytes-like object is required, not 'int'

In [ ]:
arr=np.array([1,22,3,4],dtype="f")
print(arr)
arr.dtype

[ 1. 22.  3.  4.]


dtype('float32')

In [ ]:
arr=np.array([(1+1j),(22+4j),(3+2j),(4-2j)],dtype="c")
print(arr)
arr.dtype

[b'(' b'(' b'(' b'(']


dtype('S1')

astype()

In [ ]:
arr=np.array([34,45,0,23])
print(arr.astype(bool))


[ True  True False  True]


In [ ]:
arr=np.array([[34,45,0,23]])
for i in arr:
    print (i)
    for j in i:
        print(j)

[34 45  0 23]
34
45
0
23


In [ ]:
arr=np.array([[[[34,45,0,23]]]])
for i in arr:
    print (i)
    for j in i:
        print(j)
        for k in j:
            print(k)
            for l in k:
                print(l)

[[[34 45  0 23]]]
[[34 45  0 23]]
[34 45  0 23]
34
45
0
23


np.nditer()

In [ ]:
arr=np.array([[[[34,45,0,23]]]])
for i in np.nditer(arr):
    print(i)

34
45
0
23


In [ ]:
arr=np.array([1,2,3,4,5,6,7,8,9,10])
arr.shape
# arr=np.array([1,2,3,4,5,6,7,8,9,10],[1,2,3,4,5,6,7,8,9,10])
# arr.shape
print(arr.reshape(5,2))
arr1=arr.reshape(2,5)
print(arr1)
arr1.ndim

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


2

In [ ]:
arr=np.array([[ 1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
arr.ndim
arr.reshape(2,4,2)

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12],
        [13, 14],
        [15, 16]]])

to convert to single dimension

In [ ]:
arr=np.array([[[[34,45,0,23]]]])
print(arr.ndim)
arr.reshape(-1)
#to convert to 0D


4


array([34, 45,  0, 23])

copy() and view()

In [ ]:
arr=np.array([34,45,0,23])
arr
arr_cp=arr.copy()
arr_cp
arr[0]=100
print(arr)
arr_cp

[100  45   0  23]


array([34, 45,  0, 23])

In [ ]:
arr=np.array([34,45,0,23])
arr
arr_cp=arr.view()
arr_cp
arr[0]=100
print(arr)
arr_cp

[100  45   0  23]


array([100,  45,   0,  23])

function: concatenate()

In [ ]:
arr1=np.array([34,45,0,23])
arr2=np.array([44,55,10,33])
np.concatenate([arr1,arr2])

array([34, 45,  0, 23, 44, 55, 10, 33])

function np.ndenumerate()

In [ ]:
arr=np.array(["ad","ch","vf","de"])
for idex, i in np.ndenumerate(arr):
    print(idex,i)

(0,) ad
(1,) ch
(2,) vf
(3,) de


joining arrays:stack(), by default it is row wise

In [ ]:
arr1=np.array([34,45,0,23])
arr2=np.array([44,55,10,33])
print(np.stack([arr1,arr2]))# rowwise by default
print(np.stack([arr1,arr2],axis=1))
np.stack([arr1,arr2]).ndim

[[34 45  0 23]
 [44 55 10 33]]
[[34 44]
 [45 55]
 [ 0 10]
 [23 33]]


2

In [ ]:
arr1=np.array([34,45,0,23])
arr2=np.array([44,55,10,33])
np.vstack([arr1,arr2])

array([[34, 45,  0, 23],
       [44, 55, 10, 33]])

In [ ]:
arr1=np.array([34,45,0,23])
arr2=np.array([44,55,10,33])
np.hstack([arr1,arr2])

array([34, 45,  0, 23, 44, 55, 10, 33])

In [ ]:
arr1=np.array([34,45,0,23])
arr2=np.array([44,55,10,33])
print(np.dstack([arr1,arr2]))
print(np.dstack([arr1,arr2]).ndim)
print(np.stack([arr1,arr2],axis=1))
np.stack([arr1,arr2]).ndim

[[[34 44]
  [45 55]
  [ 0 10]
  [23 33]]]
3
[[34 44]
 [45 55]
 [ 0 10]
 [23 33]]


2

In [ ]:
arr1=np.array([[[[1,2,3,4],[1,2,3,4]]]])
print(arr1.ndim)
arr2=np.array([ [[[1,2,3,4]]],[[[1,2,3,4]]] ])
arr2.ndim

4


4

In [ ]:
arr1=np.array([[34,45,0,23]])
arr2=np.array([[44,55,10,33]])

print(arr1.ndim)
print(np.stack([arr1,arr2]))
np.vstack([arr1,arr2]).shape


2
[[[34 45  0 23]]

 [[44 55 10 33]]]


(2, 4)

In [ ]:
arr1=np.array([[34,45,0,23]])
arr2=np.array([[44,55,10,33]])
np.hstack([arr1,arr2]).shape

(1, 8)

splitting of an array

In [180]:
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15])
arr1=np.array_split(arr,2)
arr1
arr1=np.array_split(arr,3)
arr1
arr1=np.array_split(arr,18)
arr1
arr1=np.array_split(arr,5)
arr1

[array([1, 2, 3]),
 array([4, 5, 6]),
 array([7, 8, 9]),
 array([10, 11, 12]),
 array([13, 14, 15])]

In [184]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15]])
arr1=np.array_split(arr,3)
arr1

[array([[1, 2, 3],
        [4, 5, 6]]),
 array([[ 7,  8,  9],
        [10, 11, 12]]),
 array([[13, 14, 15]])]

sorting an array

In [186]:
arr=np.array([34,45,67,23])
arr.sort()
arr

array([23, 34, 45, 67])

In [187]:
arr=np.array([[34,45],[67,23]])
arr.sort()
arr

array([[34, 45],
       [23, 67]])

array searching


In [190]:
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15])
np.where(arr%2==0) #it retrun the index of the value whnich satisfy the condition
np.where(arr%2==1)

(array([ 0,  2,  4,  6,  8, 10, 12, 14]),)

In [192]:
arr=np.array([1,2,3,4,5,6,7,8,9,10])
arr1=[True,True,True,False,False,True,False,True,False,True]
arr[arr1]

array([ 1,  2,  3,  6,  8, 10])

In [195]:
arr=np.array([1,2,3,4,5,6,7,8,9,10])
value=[]
for i in arr:
    if i%2==0:
        value.append(True)
    else:
        value.append(False)
print(value)
arr[value]

[False, True, False, True, False, True, False, True, False, True]


array([ 2,  4,  6,  8, 10])

arange()


In [199]:
arr=np.arange(1,11)
print(arr)
arr=np.arange(1,11,2)
arr

[ 1  2  3  4  5  6  7  8  9 10]


array([1, 3, 5, 7, 9])

function np.ones() and np.zeros()

In [202]:
arr=np.ones(5)
print(arr)
arr=np.zeros(5)
arr

[1. 1. 1. 1. 1.]


array([0., 0., 0., 0., 0.])

mathematical functions

In [221]:
arr=np.array([1,2,3,4,5,6,7,8,9,10])
arr
arr.sum()
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr.sum(axis=1))
arr=np.array([1,2,3,4,5,6,7,8,9,10])
print(np.subtract(arr,1))
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(np.subtract(arr,1))
arr=np.array([1,2,3,4,5,6,7,8,9,10])
print(np.multiply(arr,2))
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(np.multiply(arr,2))
arr=np.array([1,2,3,4,5,6,7,8,9,10])
print(np.divide(arr,2))
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(np.divide(arr,2))
arr=np.array([1,2,3,4,5,6,7,8,9,10])
print(arr.mean())
arr=np.array([100,27,34,4,55,6,7])
np.median(arr)

[15 40]
[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[ 2  4  6  8 10 12 14 16 18 20]
[[ 2  4  6  8 10]
 [12 14 16 18 20]]
[0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5. ]
[[0.5 1.  1.5 2.  2.5]
 [3.  3.5 4.  4.5 5. ]]
5.5


np.float64(27.0)

module random()


In [230]:
from numpy import random
arr=random.random()
print(arr)
arr=random.random(size=5)
print(arr)
arr=random.random(size=(3,5))
arr

0.7043561900883342
[0.90470151 0.7141332  0.55932388 0.83520987 0.06207497]


array([[0.78596251, 0.94105309, 0.40148451, 0.09720269, 0.11590593],
       [0.87219608, 0.09120113, 0.11381596, 0.95212379, 0.56361671],
       [0.49547727, 0.88341375, 0.3703964 , 0.83422044, 0.36437956]])

In [ ]:
arr=random.rand() #we cant give size method in rand
arr

0.769702405895101

In [234]:
arr=random.randint(1,100,size=3)
arr

array([28, 32, 74], dtype=int32)

In [235]:
arr=random.randint(1,100,size=(3,5))
arr

array([[47, 19, 46,  2, 43],
       [78, 84, 70, 28,  9],
       [70, 43, 82, 81, 20]], dtype=int32)