In [16]:
# pip install numpy

In [17]:
import numpy as np

In [18]:
np.__version__

'1.26.4'

In [3]:
import numpy as np

In [24]:
df = np.array([[[[12,34,12,4,5],[56,78,90,34,65],[23,34,56,12,34]]]])
df.ndim

4

In [ ]:
df = np.array([ [[[[[[[[[[[[ [12,34,12,4,5]]]]]]]]]]]]]])
df

array([[[[[[[[[[[[[[12, 34, 12,  4,  5]]]]]]]]]]]]]])

In [6]:
# pip install numpy

In [7]:
a = [1,2,34,5]

In [8]:
df = np.array(45)
df.ndim

0

In [60]:
df = np.array([[[[[[[[[[[[1,2,3]]]]]]]]]]]])

for i in np.nditer(df):
    print(i)

1
2
3


In [57]:
df = np.array([[[1,2,3]]])

for i in df:
    for j in i:
        for k in j:
            print(k)

1
2
3


In [51]:
df = np.array([1,2,3])
df.ndim
df.max()

3

In [ ]:
# zero dimensional array
df =np.array(45)
print(df.ndim )        # ndim is used for find the array dimension
# it is an 1-dimensional array 
x =[1,2,3,4,5]
y =np.array(x)

print(y.ndim)

# a =[[12,23,34,45,56]]
# # # it is an 2 dimensional array

y =np.array(x)
y.ndim

# # it is an 3 dimensional array
x =[[[[1,2,3]],[[4,5,6]],[[1,2,3]],[[4,5,6]]]]
y =np.array(x)
print(y)
y.ndim

0
1
[[[[1 2 3]]

  [[4 5 6]]

  [[1 2 3]]

  [[4 5 6]]]]


4

In [ ]:
a = np.array([[[[35,67,78]]],[[[25,50,67]]],[[[23,10,11]]]])
a[1,0,0,0]

25

In [ ]:
# we create the array dimension

import numpy as np

x =[[32,2,45],[21,3,5]]
y =np.array(x, ndmin=10)
print(y)
y.ndim

[[[[[[[[[[32  2 45]
         [21  3  5]]]]]]]]]]


10

In [ ]:
arr = np.array([[[[[[[[23,45,34,56],[56,78,90,100]]]]]]]])
arr[7,3]                                      

IndexError: index 7 is out of bounds for axis 0 with size 1

In [ ]:
y = np.array([[1,2,4,5],[6,3,5,6]])


print(y[1,2])

5


In [ ]:
# indexing array
# x =np.array(['hello ',26,'world'])
# print(x[0] + x[1])
x= [[[23,44,2],[34,12,76]], [[23,35,12],[45,65,15]]]
y =np.array(x)
y[0,1,2]

np.int64(76)

In [ ]:
import numpy as np

In [ ]:
df = np.array([[[[1,2,3,4,5,6,7,8,9,10]],[[11,22,33,44,55,66,77,8,9,10]]]])
df[0,1,0,0]

np.int64(11)

In [ ]:
df = np.array([[1,2,3],[4,5,6]])
print(df[0,0])

1


- Store student marks in a list, display them using a line plot, and show the same data using a bar chart.
- Read student marks from a CSV file and display them using a line plot and bar chart.

In [ ]:
df = np.array([[1,2,3],[4,5,6],[7,8,9]])
df[2,1]


np.int64(8)

In [ ]:


# y =np.array([[[[23,34,2],[34,12,76],[78,45,65],[90,43,87]]]])
# print(y[0,0,2,2])
y =np.array([[[[[[[[[[[23,34,2]]],[[[34,12,76]]],[[[78,45,65]]],[[[90,43,87]]]]]]]]]]])
y.ndim
# y[0,0,0,0,0,0,3,0,0,2]  
y = np.array([[[[[[[[[[[23,34,2]]]]],  [  [[[ [34,12,76]]]]]]]]]]])    
y[0,0,0,0,0,1,0,0,0,0,2]


np.int64(76)

In [ ]:
# x = ("hello world")
# print(x[0:2],x[6:11])
# df =len(x)
# print(df)

y = [1,2,34,5,5,6,7,8,9]
y[2:]

[34, 5, 5, 6, 7, 8, 9]

In [ ]:
for i in range(1, 11,2):
    print(i)

1
3
5
7
9


In [ ]:
df = np.array([1,2,34,5,5,6,7,8,9])
df[::-1] #start, stop, step

array([ 9,  8,  7,  6,  5,  5, 34,  2,  1])

In [ ]:
# array slicing

df =np.array([23,34,12,24,45])
print(df[0:2],df[3:])


[23 34] [24 45]


In [ ]:
for i in range(1,10,3):
    print(i)

1
4
7


In [ ]:
df =np.array([23,34,12,24,45,78,44,55])
print(df[::2])    #start ,stop ,step   format

[23 12 45 44]


In [ ]:
df =np.array([ [[23,34,12,24,45],[1,2,3,4,5],[10,11,12,13,14]]])
print(df[0,2,2:4])
# df[0,2,1:3]

[12 13]


In [ ]:
import numpy as np

In [ ]:
df =np.array([[23,34,12,24,45],[1,2,3,4,5],[11,12,13,14,15],[23,34,12,24,45],[1,2,3,4,5],[22,12,13,14,15],[23,34,12,24,45],[1,2,3,4,5],[33,12,13,14,15]])

df[::2]
# df.shape

array([[23, 34, 12, 24, 45],
       [11, 12, 13, 14, 15],
       [ 1,  2,  3,  4,  5],
       [23, 34, 12, 24, 45],
       [33, 12, 13, 14, 15]])

In [ ]:
df =np.array([[23,34,12,24,45],
              [1,2,3,4,5],
              [11,12,13,14,15]])

print(df[2, 0:3])  # Slicing rows and columns

[11 12 13]


| Code | Meaning          | Example                         |
| ---- | ---------------- | ------------------------------- |
| `i`  | Integer          | `int8`, `int32`, `int64`        |
| `bool`  | Boolean          | `True`, `False`                 |
| `u`  | Unsigned Integer | `uint8`, `uint16`, `uint32`     |
| `f`  | Float            | `float16`, `float32`, `float64` |
| `c`  | Complex Float    | `complex64`, `complex128`       |
| `m`  | Timedelta        | Time duration                   |
| `M`  | Datetime         | Date and time                   |
| `O`  | Object           | Python objects                  |
| `S`  | Byte String      | Binary strings                  |
| `U`  | Unicode String   | Text strings                    |
| `V`  | Void             | Raw memory blocks               |


| NumPy Code | NumPy Data Type                           | Closest Python Data Type | Difference                                                                       |
| ---------- | ----------------------------------------- | ------------------------ | -------------------------------------------------------------------------------- |
| `i`        | Integer (`int8`, `int32`, `int64`)        | `int`                    | Python `int` has no fixed size, NumPy integers have fixed sizes.                 |
| `bool`     | Boolean                                   | `bool`                   | Same purpose, but NumPy stores values efficiently in arrays.                     |
| `u`        | Unsigned Integer (`uint8`, `uint16`)      | No direct equivalent     | Python `int` supports negative values, NumPy `uint` stores only positive values. |
| `f`        | Float (`float16`, `float32`, `float64`)   | `float`                  | Python float is usually 64-bit; NumPy offers multiple precisions.                |
| `c`        | Complex Float (`complex64`, `complex128`) | `complex`                | Same concept, but NumPy controls memory size.                                    |
| `m`        | Timedelta                                 | `datetime.timedelta`     | NumPy optimized for array operations on durations.                               |
| `M`        | Datetime                                  | `datetime.datetime`      | NumPy optimized for storing many dates in arrays.                                |
| `O`        | Object                                    | Any Python object        | Stores Python objects inside NumPy arrays.                                       |
| `S`        | Byte String                               | `bytes`                  | Stores strings as binary bytes.                                                  |
| `U`        | Unicode String                            | `str`                    | Stores Unicode text efficiently in arrays.                                       |
| `V`        | Void                                      | No direct equivalent     | Stores raw memory blocks or binary structures.                                   |


| Code   | Data Type        | Description                                     | Example Code                                   | Output                          |
| ------ | ---------------- | ----------------------------------------------- | ---------------------------------------------- | ------------------------------- |
| `i`    | Integer          | Stores whole numbers (positive, negative, zero) | `np.array([10, -5, 100], dtype='i')`           | `[ 10  -5 100 ]`                |
| `bool` | Boolean          | Stores only `True` or `False` values            | `np.array([True, False, True], dtype=bool)`    | `[ True False True ]`           |
| `u`    | Unsigned Integer | Stores only positive whole numbers and zero     | `np.array([0, 25, 255], dtype='uint8')`        | `[  0  25 255 ]`                |
| `f`    | Float            | Stores decimal numbers                          | `np.array([3.14, 5.5, -2.7], dtype='f')`       | `[ 3.14  5.5  -2.7 ]`           |
| `c`    | Complex Float    | Stores real and imaginary parts                 | `np.array([3+4j, 2-1j], dtype='c')`            | `[3.+4.j 2.-1.j]`               |
| `m`    | Timedelta        | Stores time duration                            | `np.array([5], dtype='timedelta64[D]')`        | `[5 days]`                      |
| `M`    | Datetime         | Stores date and time                            | `np.array(['2026-06-11'], dtype='datetime64')` | `['2026-06-11']`                |
| `O`    | Object           | Stores mixed Python objects                     | `np.array([100, "Hello", [1,2,3]], dtype='O')` | `[100 'Hello' list([1, 2, 3])]` |
| `S`    | Byte String      | Stores strings as bytes                         | `np.array(['Hello'], dtype='S')`               | `[b'Hello']`                    |
| `U`    | Unicode String   | Stores Unicode text                             | `np.array(['Hello'], dtype='U')`               | `['Hello']`                     |
| `V`    | Void             | Stores raw memory blocks                        | `np.array([(1,2)], dtype='V8')`                | Raw binary data                 |


In [ ]:
import numpy as np

arr = np.array([10, -5.8, 100], dtype='i')
print(arr)
print(arr.dtype)

[ 10  -5 100]
int32


In [ ]:
arr = np.array([1, 0, 4], dtype=bool)
print(arr)
print(arr.dtype)

[ True False  True]
bool


In [ ]:
x = 2
print(x**16)

65536


In [ ]:
pip install numpy==1.26.4


[notice] A new release of pip is available: 25.3 -> 26.1.2
[notice] To update, run: python3 -m pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.


In [ ]:
import numpy
numpy.__version__

'1.26.4'

In [ ]:
(2 **32)-25 

4294967271

In [ ]:
arr = np.array([10, -25, 100], dtype='uint32') 
print(arr)
print(arr.dtype)

[        10 4294967271        100]
uint32


/var/folders/6t/1x0dp_9s65b8v_4nrll53hdw0000gn/T/ipykernel_12453/1900734789.py:1: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of -25 to uint32 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)
will give the desired result (the cast overflows).
  arr = np.array([10, -25, 100], dtype='uint32')


In [ ]:
arr = np.array([3, 5, -2], dtype='f')
print(arr)
print(arr.dtype)

[ 3.  5. -2.]
float32


In [ ]:
arr = np.array([3+4j, 2-1j], dtype='complex128')
print(arr)
print(arr.dtype)

[3.+4.j 2.-1.j]
complex128


In [ ]:
arr = np.array([5], dtype='timedelta64[D]')
print(arr)
print(arr.dtype)

[5]
timedelta64[D]


In [ ]:
arr = np.array(['2026-06-11'], dtype='datetime64')
print(arr)
print(arr.dtype)

['2026-06-11']
datetime64[D]


In [ ]:
arr = np.array([100, "Hello", [1,2,3]], dtype='O')
print(arr)
print(arr.dtype)

[100 'Hello' list([1, 2, 3])]
object


In [ ]:
arr = np.array(['Hello','hidfdsdsd'], dtype='S')
print(arr)
print(arr.dtype)

[b'Hello' b'hidfdsdsd']
|S9


In [ ]:
arr = np.array(['hello'], dtype='U')
print(arr)
print(arr.dtype)

['hello']
<U5


In [ ]:
try:
    print("hi")
    a = ["jebi","guna","arya"]
    df = np.array(a, dtype="f")
    print(df)
    df.dtype
except NameError:
    print("please enter currect syntax")
except Exception as e:
    print("you got an error", e)
finally:
    print("called")

hi
you got an error could not convert string to float: 'jebi'
called


In [ ]:
a = [1,2,0,4,0,60,0]
df = np.array(a, dtype="bool")
print(df)
print(df.dtype)

[ True  True False  True False  True False]
bool


In [ ]:

a = ["jebin","guna","arya"]
df = np.array(a, dtype="U")
print(df)
df.dtype

['jebin' 'guna' 'arya']


dtype('<U5')

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4],dtype="f")
print(arr)
print(arr.dtype)

arr = np.array(['a','blessing','c'])
print(arr)
print(arr.dtype)

arr = np.array([1, 22, 3, 4], dtype='S')  #converting data types 
print(arr)
print(arr.dtype)

# arr = np.array(['jebin star','shilpa s nairs','vismaya a s'], dtype="S")
# arr.dtype


[1. 2. 3. 4.]
float32
['a' 'blessing' 'c']
<U8
[b'1' b'22' b'3' b'4']
|S2


In [ ]:
arr =[1, 2, 3, 4]
df = np.array(arr)
df.astype("m")
print(df)
df.dtype

[1 2 3 4]


dtype('int64')

In [ ]:
arr = np.array([1.1, 2.6, 3.1])
# arr.dtype

newarr = arr.astype('i')

# print(newarr.dtype)
newarr

array([1, 2, 3], dtype=int32)

In [ ]:
arr2 = np.array([1, 0, 3, 5, 7, 8, 0, 0])
newarr2 = arr2.astype("bool") 
# print(newarr2)#[ True False True]
# print(newarr2.dtype)
newarr2

array([ True, False,  True,  True,  True,  True, False, False])

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
y = arr.view()

arr[0] = 97
print(arr)
print(x)
print(y)

[97  2  3  4  5]
[1 2 3 4 5]
[97  2  3  4  5]


In [ ]:
arr = np.array([[[[[[[[[[[[[[1, 2, 3, 4, 5],[11, 12,13, 14, 15]]]]]]]]]]]]]])
for i in np.nditer(arr):
    print(i)

1
2
3
4
5
11
12
13
14
15


In [ ]:
arr = np.array([1, 2, 3, 4, 5])
print(arr.shape)

(5,)


In [ ]:
arr = np.array([[1, 2, 3, 4, 5],[11, 12,13, 14, 15]])
print(arr.shape)

(2, 5)


In [ ]:
arr = np.arange(1, 18, 2)
np.array(arr, ndmin=2)

array([[ 1,  3,  5,  7,  9, 11, 13, 15, 17]])

In [ ]:
arr = np.zeros((3,4))
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
arr1 = np.array([1, 2, 3, 4, 5])
print(arr1*2)
print(arr1+2)
print(arr1-2)


[ 2  4  6  8 10]
[3 4 5 6 7]
[-1  0  1  2  3]


In [ ]:
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([11, 12,13, 14, 15])
arr1*arr2

array([11, 24, 39, 56, 75])

In [ ]:
a = {1,2,4,5}
a.add(34)
a

{1, 2, 4, 5, 34}

In [ ]:
a = [1,2,4,5]
a.append(34)
a

[1, 2, 4, 5, 34]

In [ ]:
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([11, 12,13, 14, 15])
arr3 = np.array([11, 12,13, 14, 15])

arr = np.vstack([arr1,arr2,arr3]) # 0 row, 1 column
arr


array([[ 1,  2,  3,  4,  5],
       [11, 12, 13, 14, 15],
       [11, 12, 13, 14, 15]])

In [ ]:
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([11, 12,13, 14, 15])
arr4 = np.array([23,45,67,89])

arr3 = np.concatenate([arr4, arr2, arr1])
arr3

array([23, 45, 67, 89, 11, 12, 13, 14, 15,  1,  2,  3,  4,  5])

In [ ]:
arr = np.array([[[[1, 2, 3, 4, 5],[11, 12,13, 14, 15]]]])
for i in arr:
    for j in i:
        for k in j:
            for l in k:
                print(l)

1
2
3
4
5
11
12
13
14
15


In [ ]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 38
# print(arr)
print(x)

[1 2 3 4 5]


In [ ]:
arr = np.array([1, 2, 3, 4, 5])
y = arr.view()
arr[0] = 38
print(y)
arr

[38  2  3  4  5]


array([38,  2,  3,  4,  5])

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
x[4] = 31
print(arr)#[31 2 3 4 5]
print(x)#[31 2 3 4 5]

[ 1  2  3  4 31]
[ 1  2  3  4 31]


In [ ]:
df = np.array([[1,2,3,4],[4,5,6,7],[7,8,9,10]])
df.shape # columns and rows
# df

(3, 4)

In [ ]:
import numpy as np

x = np.array([[[[[[[[[2, 3, 4, 5, 6]]], [[[4, 5, 6, 7, 0]]], [[[9, 8, 7, 6, 5]]]]]]]]])  # Added a zero to match lengths
print(x.shape)
# x.ndim
# not its my own not usable

(1, 1, 1, 1, 1, 3, 1, 1, 5)


In [ ]:
df = np.array([[[1,2,3,4],[4,5,6,7],[7,8,9,10]]])
print(df)
for i in df:
    for j in i:
        for k in j:
            print(k)

[[[ 1  2  3  4]
  [ 4  5  6  7]
  [ 7  8  9 10]]]
1
2
3
4
4
5
6
7
7
8
9
10


In [ ]:
x = np.array([[[[[[1,2,3,4,5]]]]]])
for i in np.nditer(x):
    print(i)

1
2
3
4
5


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
arr1 = np.array_split(arr, 15)
arr1[2]

array([3])

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
np.array_split(arr, 15)

[array([1]),
 array([2]),
 array([3]),
 array([4]),
 array([5]),
 array([6]),
 array([7]),
 array([8]),
 array([9]),
 array([10]),
 array([11]),
 array([12]),
 array([], dtype=int64),
 array([], dtype=int64),
 array([], dtype=int64)]

In [ ]:
arr = np.array([[11,12,14],[1,2,4],[1,2,4],[1,2,4],[1,2,4],[1,2,4],[1,2,4],[1,2,4],[1,2,4]])
np.array_split(arr[0], 6)

[array([11]),
 array([12]),
 array([14]),
 array([], dtype=int64),
 array([], dtype=int64),
 array([], dtype=int64)]

In [ ]:
arr = np.array([5,4,3,2,1])
np.sort(arr)

array([1, 2, 3, 4, 5])

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 2, 1 ,3])
print(np.sum(arr))
print(np.mean(arr))
print(np.median(arr))
print(np.max(arr))
print(np.min(arr))
print(np.subtract(arr, 1))
print(np.unique(arr))


21
2.625
2.5
5
1
[0 1 2 3 4 1 0 2]
[1 2 3 4 5]


In [ ]:
import pandas as pd
value = {"Username":["jebi","guna","arya","noha"],"age":[27,25,25,28]}
df = pd.DataFrame(value)

for i ,j in np.ndenumerate(df):
    print(i)
    print(j)

(0, 0)
jebi
(0, 1)
27
(1, 0)
guna
(1, 1)
25
(2, 0)
arya
(2, 1)
25
(3, 0)
noha
(3, 1)
28


In [ ]:
arr = np.array([11, 12, 13, 4, 5])
arr2 = np.array([12,23,13,14,15])
arr+arr2

array([23, 35, 26, 18, 20])

In [ ]:
def sum(x,y):
    return x**y

some = np.frompyfunc(sum, 2,1)

ar = [1,2,3]
ar2 = [3,4,5]
some(ar, ar2)

array([1, 16, 243], dtype=object)

In [ ]:
arr2 = np.array([12,23,9,14,15,1])
arr = []
for i in arr2:
    if i >= 10:
        arr.append(True)
    else:
        arr.append(False)

arr2[arr]

array([12, 23, 14, 15])

In [ ]:
arr = np.array([[[1,2,4],[1,2,4],[1,2,4]],[[1,2,4],[1,2,4],[1,2,4]],[[1,2,4],[1,2,4],[1,2,4]],[[1,2,4],[1,2,4],[1,2,4]]  ])
arr.size

36

In [ ]:
[[2,45],[1,2],[3,4]]

In [ ]:
[  ,  [[3,4],[2,4],[2,4]],  [[3,5],[2,4],[2,4]]]

[[1,2,],[3,4]]

[  [[1,2,4],[1,2,4],[1,2,4]],[[1,2,4],[1,2,4],[1,2,4]],[[1,2,4],[1,2,4],[1,2,4]],[[1,2,4],[1,2,4],[1,2,4]]  ]

[[[1, 2, 4], [1, 2, 4], [1, 2, 4]],
 [[1, 2, 4], [1, 2, 4], [1, 2, 4]],
 [[1, 2, 4], [1, 2, 4], [1, 2, 4]],
 [[1, 2, 4], [1, 2, 4], [1, 2, 4]]]

1) Generate an array of 10 random integers between 1 and 100.
2) Find the length of a given NumPy array.
3) Find the maximum value in an array.
4) Find the minimum value in an array.

In [ ]:
arr = np.arange(1, 11) #18
# print(arr)
# arr.reshape(3, 3, 2) # 3 blocks, 3 rows, 2 columns
# arr.reshape(5,2,1) # 5*2*1 = 10

arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
newarr = arr.reshape(8, 1)
newarr

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [ ]:
arr = np.array([[[[[[1, 2, 3, 4, 5, 6, 7, 8]]]]]])
arr

array([[[[[[1, 2, 3, 4, 5, 6, 7, 8]]]]]])

In [ ]:
arr = np.array([[[[[[1, 2, 3, 4, 5, 6, 7, 8]]]]]])
newarr = arr.reshape(-1)
# arr.ndim
newarr.ndim

1

In [ ]:
# Numpy iterating

arr = np.array([1, 2, 3])
# print(arr)
for x in arr:
    print(x) #1 2 3


1
2
3


In [ ]:
arr = np.array([[[[[1, 2, 3], [4, 5, 6]]]]])
x =arr.reshape(-1)
x
for i in x:
    print(i) #[1 2 3]

1
2
3
4
5
6


In [ ]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11,12]]])
for x in arr:
    print("x represents the 2-D array:")
    print(x)



x represents the 2-D array:
[[1 2 3]
 [4 5 6]]
x represents the 2-D array:
[[ 7  8  9]
 [10 11 12]]


In [ ]:
arr = np.array([[[[[[[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11,12]]]]]]]])

# for x in arr:
#     for y in x:
#         for z in y:
#             print(z)

for i in np.nditer(arr):
    print(i) 

1
2
3
4
5
6
7
8
9
10
11
12


In [ ]:
df = np.array([[23, 45, 33, 45], [1, 2, 3, 4], [5, 6, 78, 9]])

for i in df:
    for j in i:
        print(j)

23
45
33
45
1
2
3
4
5
6
78
9


In [ ]:
arr = np.array([[[1, 2, 3]], [[4, 5, 6]], [[7, 8, 9]], [[10, 11,12]]])

 #  before you using forloop again and again but this is finish a single line

for i in np.nditer(arr):
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12


In [ ]:

a=np.array([1,2,3])

for i in np.nditer(a, flags=["buffered"],op_dtypes=["float"]):
    print(i)

a

1.0
2.0
3.0


array([1, 2, 3])

In [ ]:

a=np.array([[1,2,3]])
y = np.nditer(a,flags=['buffered'],op_dtypes=['float'])
for x in y:
    print(x)


1.0
2.0
3.0


In [ ]:
#  Iterating Array With Different Data Types

a=np.array([[[1,2,3,1,3]]])
for x in np.nditer(a,flags=['buffered'], op_dtypes=['float']):
    print(x) 

for x in np.nditer(a,flags=['buffered'],op_dtypes=['complex128']):
    print(x)

for x in np.nditer(a,flags=['buffered'],op_dtypes=['S']):
    print(x)

1.0
2.0
3.0
1.0
3.0
(1+0j)
(2+0j)
(3+0j)
(1+0j)
(3+0j)
np.bytes_(b'1')
np.bytes_(b'2')
np.bytes_(b'3')
np.bytes_(b'1')
np.bytes_(b'3')


In [ ]:
#  joining

arr1 =np.array([1,2,3])
arr2 =np.array([6,7,8,9])
arr3 =np.array([11,7,8,9])
arr4 =np.array([6,7,8,9])   # default concate row wise

arr =np.concatenate([arr4,arr3,arr2,arr1])
print(arr)


[ 6  7  8  9 11  7  8  9  6  7  8  9  1  2  3]


In [ ]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])   # default join row wise
arr = np.concatenate((arr1, arr2))
print(arr)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [ ]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2),axis=0) # 0 - row, 1 - column
print(arr)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [ ]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.stack((arr1, arr2)) # default concate row
print(arr)#[[1 4]
# [2 5]
# # [3 6]]
# arr = np.stack((arr1, arr2), axis=0)
# print(arr)

[[1 2 3]
 [4 5 6]]


In [ ]:
arr1 = np.array([[1, 2, 3],[4,5,6]])   #print horizontally
arr2 = np.array([[5,11,14],[7,8,9]]) # concate column wise
arr = np.hstack([arr1, arr2])
print(arr)    

[[ 1  2  3  5 11 14]
 [ 4  5  6  7  8  9]]


In [ ]:
arr1 = np.array([[1, 2, 3],[5,7,12]])  
arr2 = np.array([[4, 5, 6],[7,8,9]])  # concate row wise
arr = np.vstack((arr1, arr2))
print(arr)

[[ 1  2  3]
 [ 5  7 12]
 [ 4  5  6]
 [ 7  8  9]]


In [ ]:
arr1 = np.array([[1, 2, 3,7],[4,5,6,7]])  
arr2 = np.array([[4, 5, 6,7],[7,8,9,7]])   # concate column wise
arr3 = np.array([[4, 5, 6,7],[7,8,9,7]])  
arr = np.dstack((arr1, arr2, arr3))
print(arr)

[[[1 4 4]
  [2 5 5]
  [3 6 6]
  [7 7 7]]

 [[4 7 7]
  [5 8 8]
  [6 9 9]
  [7 7 7]]]


In [ ]:
# array splitting
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 10)
print(newarr)
newarr[5]

[array([1]), array([2]), array([3]), array([4]), array([5]), array([6]), array([], dtype=int64), array([], dtype=int64), array([], dtype=int64), array([], dtype=int64)]


array([6])

In [ ]:
#Split Into Arrays

arr = np.array([1, 2, 3, 4, 5, 6, 7])
newarr = np.array_split(arr, 4)
print(newarr)
print(newarr[0])
# print(newarr[1])
# print(newarr[2])

# for i in newarr:
#     print(i)

[array([1, 2]), array([3, 4]), array([5, 6]), array([7])]
[1 2]


In [ ]:
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])
newarr = np.array_split(arr, 4)
newarr

[array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]]),
 array([[ 9, 10]]),
 array([[11, 12]])]

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12],[13, 14, 15], [16, 17, 18]])
newarr = np.array_split(arr, 5, axis=1)
newarr

[array([[ 1],
        [ 4],
        [ 7],
        [10],
        [13],
        [16]]),
 array([[ 2],
        [ 5],
        [ 8],
        [11],
        [14],
        [17]]),
 array([[ 3],
        [ 6],
        [ 9],
        [12],
        [15],
        [18]]),
 array([], shape=(6, 0), dtype=int64),
 array([], shape=(6, 0), dtype=int64)]

In [ ]:
#  NumPy Searching Arrays

arr = np.array([1, 7,2, 3, 7,4, 5, 4, 4,6,7,8,89,7,9])
x = np.where(arr %2 == 0)   #  it will show where ever have that value print in index
x


(array([ 2,  5,  7,  8,  9, 11]),)

In [ ]:
arr = np.array([11, 22, 3, 1, 3, 6, 7, 8])
x = np.where(arr >4)      # which one have the reaching values
print(x)

(array([0, 1, 5, 6, 7]),)


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
x = np.where(arr %2 == 0)
print(x)         # reaching odd number index 

(array([1, 3, 5, 7]),)


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
arr.mean()
arr.sum()
arr*2
# arr

array([ 2,  4,  6,  8, 10, 12, 14, 16])

In [ ]:
arr = np.array([3, 2, 0, 1,7,8,5]) 
print(np.sort(arr))
np.argsort(arr)

[0 1 2 3 5 7 8]


array([2, 3, 1, 0, 6, 4, 5])

In [ ]:
#   NumPy Sorting Arrays

arr = np.array([3, 2, 0, 1,7,8,5]) 
print(arr)
print(np.sort(arr))
np.argsort(arr)  # it will show the index of the sorted array
# # # # print decreasing order
np.argsort(arr)[::-1]  # reverse the sorted array

[3 2 0 1 7 8 5]
[0 1 2 3 5 7 8]


array([5, 4, 6, 0, 1, 3, 2])

In [ ]:
a = [3, 2, 0, 1,7,8,5]
x = np.array([3, 2, 0, 1,7,8,5])

# print(a)
# x*2

In [ ]:
arr = np.array([41, 42, 43, 44])
x = np.array([True, False, True, False]) 
# print(x)
# arr[x]
arr[x]

array([41, 43])

In [ ]:
# def demo(x,y,z):
#     return x+y+z

# demo(5,7,8)


x = lambda a, b, c : a+b+c

x(6,2,4)

12

In [ ]:
arr = np.array([41, 42, 48, 43, 44, 45, 46, 47, 48, 49, 50, 51])

new = arr >=45
new
arr[new]

array([48, 45, 46, 47, 48, 49, 50, 51])

In [ ]:
df = np.zeros(3)
df
df = np.ones(5)
df

array([1., 1., 1., 1., 1.])

In [ ]:
arr = np.array([41, 42, 48, 43, 44, 45, 46, 47, 48, 49, 50, 51])






# x = []
# for i in arr:
#     if i>45:
#         x.append(True)
#         print(i)
#     else:
#         x.append(False)


# arr[x]




In [ ]:
#NumPy Filter Array

arr = np.array([41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51])

filter_arr = []

for element in arr:
# if the element is higher than 42, set the value to True,
# otherwise False:
    if element < 45:
        filter_arr.append(True)
    else:
        filter_arr.append(False)
arr[filter_arr]

array([41, 42, 43, 44])

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
# Create an empty list
filter_arr = []
# go through each element in arr
for element in arr:
# if the element is completely divisible by 2, set the value to
#True, otherwise False
    if element % 2 == 0:
        filter_arr.append(True)
    else:
        filter_arr.append(False)
newarr = arr[filter_arr]
print(filter_arr)#[False, True, False, True, False, True, False]
print(newarr)

[False, True, False, True, False, True, False, True]
[2 4 6 8]


In [ ]:
arr = np.array([41, 42, 43, 44])
filter_arr = arr > 42
newarr = arr[filter_arr]
print(filter_arr)
print(newarr)

[False False  True  True]
[43 44]


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
filter_arr = arr % 2 == 0
newarr = arr[filter_arr]
print(filter_arr)#[False True False True False True False]
print(newarr)#[2 4 6]

[False  True False  True False  True False]
[2 4 6]


In [ ]:
from numpy import random
x = random.randint(10)
x

8

In [ ]:
x = random.randint(10, 100, size=(3,5))
x

array([[98, 25, 32, 28, 19],
       [64, 50, 55, 66, 82],
       [48, 81, 61, 13, 13]])

In [ ]:
x = random.rand()
print(x)#0.30894271886494806

0.26668249741847105


In [ ]:
x=random.randint(1000, 9999, size=4)
print(x)#[56 42 47 34 71]


[4166 7513 4780 8523]


In [ ]:
x = random.randint(1000, 9999, size=(3, 4))
print(x)#[[90 99 11 30 34] [66 40 63 36 37] [63 35 89 51 58]]

[[3892 4616 2969 1553]
 [2716 9116 7727 1965]
 [8756 9230 2823 7475]]


In [ ]:
x = random.rand(3,5)
print(x)#[0.2781381 0.8315005 0.7296363 0.5482757 0.8660564]


[[0.70571763 0.90545023 0.10461352 0.35556355 0.02875507]
 [0.09062245 0.1886987  0.86269624 0.75925065 0.9470976 ]
 [0.78423664 0.35535813 0.4209898  0.43157112 0.82875887]]


In [ ]:
x = random.rand(3, 5)
print(x)#[[0.03379952 0.78263517 0.9834899 0.47851523
# 0.02948659]
# [0.36284007 0.10740884 0.58485016 0.20708396 0.00969559]
# [0.88232193 0.86068608 0.75548749 0.61233486 0.06325663]]

[[0.86211784 0.57681911 0.40232632 0.36476377 0.2788229 ]
 [0.49327125 0.30918259 0.96597827 0.29517531 0.5575358 ]
 [0.78575077 0.02664063 0.09853822 0.26543757 0.4070955 ]]


In [ ]:
y = ['hi','hello','bye','goodbye']
x = random.choice(y)
# x = random.choice([3, 5, 7, 9])
print(x)


hello


In [ ]:
x = random.choice([3, 5, 7, 9], size=(3,3))
print(x)


[[9 7 3]
 [7 5 3]
 [5 7 5]]


In [ ]:
x = random.choice([3, 5, 7, 9],size=(3, 5))
print(x)#[[7 5 3 5 7]

[[5 7 5 9 5]
 [9 5 3 7 9]
 [9 3 9 9 3]]


In [ ]:
arr = np.array([1, 2, 3, 4, 5])
random.shuffle(arr)
# print(arr)#[4 1 2 5 3]
arr

array([2, 3, 5, 1, 4])

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
random.permutation(arr)#[2 3 5 4 1]


array([3, 4, 5, 2, 1])

In [ ]:
import numpy as np

def square(x, y):
    return x ** y

square_ufunc = np.frompyfunc(square, 2, 1) # 1 (number of inputs), 1 (number of output)

arr = np.array([1, 2, 3, 4, 5])
arr2 = np.array([1, 2, 3, 4, 5])

print(square_ufunc(arr,arr2))

[1 4 27 256 3125]


In [ ]:
import random
choose = ['stone','paper','siccers']
my_count = 0
com_count = 0

while True:
    computer = random.choice(choose)
    me = input("enter your value")
    if computer == me:
        print("draw")
    elif computer == 'stone' and me == 'paper':
        my_count += 5
        print(f"computer score :{com_count} and your score : {my_count}")
    elif computer == 'paper' and me == 'stone':
        com_count += 5
        print(f"computer score :{com_count} and your score : {my_count}")
    elif computer == 'paper' and me == 'siccers':
        my_count += 5
        print(f"computer score :{com_count} and your score : {my_count}")
    elif computer == 'siccers' and me == 'paper':
        com_count += 5
        print(f"computer score :{com_count} and your score : {my_count}")
    elif computer == 'siccers' and me == 'stone':
        my_count += 5
        print(f"computer score :{com_count} and your score : {my_count}")
    elif computer == 'stone' and me == 'siccers':
        com_count += 5
        print(f"computer score :{com_count} and your score : {my_count}")

    if my_count >= 50:
        print(f"you win / computer score :{com_count} and your score : {my_count}")
        break
    elif com_count >= 50:
        print(f"computer win / computer score :{com_count} and your score : {my_count}")
        break

computer score :0 and your score : 5
computer score :0 and your score : 10
computer score :0 and your score : 15
computer score :0 and your score : 20
computer score :0 and your score : 25
computer score :5 and your score : 25
computer score :5 and your score : 30
computer score :5 and your score : 35
computer score :10 and your score : 35
computer score :15 and your score : 35
computer score :15 and your score : 40
draw
draw
draw
computer score :20 and your score : 40
computer score :25 and your score : 40
computer score :25 and your score : 45
computer score :25 and your score : 50
you win / computer score :25 and your score : 50
